language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: npm release
      node_js: 10
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: master
