language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: UiQTXOJ7UuVXxj4wpcExB/YVZhjnB1pyBTBlcVLIzC9Juo1XezwjI1Q9kCuwGvNKN5FxDp0wtsIJTnFz8KXRaReFSXAyGNEJMU4QnOVMkaQvLBKt/Zys4KZYr0dwmuhEpgnHaZA8+WyhkDhmECiLR7la7u9ffEfF3BVN+YTnGk8etvltQG2SNRXpHmGbfEhvzf8rAILlQ+xoaYlQHh08t/QfpEdlz3NBAJB7SaVGi8rvCr+JZMeFSfD1K77oEsvnvD6wO90G9x4GLYEzZcm5ubxDudxcCAJOUfIYNtakin1YT/o4fsDIvVL8VxtGCrC06bkhERDymfWFAn4XDXrItdnXcwC+CGeoCjbSB9DHW0LiG6xS5fOckBVLvHw0fTNmH1lPnKk5J6u9DNXLhoB/rnjeIbfnfT1mSTFI2GEeDyncPL14B7j8qHe4uah6fN8YwVThu7oefJWtRUOV12WsbfE+7/ijBuOHPqiY+JMbYT0UZ7gRafW5FqLL2uwaQJFX9IMAoZuCu1xQ8q/aShOYeKkHPo5pFFytQPFGF9fd96JYr0VIeCx/XYuJrw2bWWJfoF67W77h6l7VDeGq9JVCYpN1XSKxKMpFT2lO9qBRMu2L2jhXYhzHT2TtjjA84YKmyNVeVjdym5IgV2fdsvHhILpSAxBv1W0xyi7/VPEhu0A=
